services:
  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    volumes:
#      - ".docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - ".docker/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./:/var/www/html:ro"
    ports:
      - "${FORWARD_HOST:-}:${FORWARD_WWW_PORT:-80}:80"
    depends_on:
      - php
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
      args:
        DOCKER_GID: '${DOCKER_GID:-1000}'
        DOCKER_UID: '${DOCKER_UID:-1000}'
    ports:
      - "${VITE_PORT:-5173}:5173"
    volumes:
      - "./:/var/www/html"
    depends_on:
      - mysql
    environment:
      XDEBUG_MODE: "${DOCKER_XDEBUG_MODE:-off}"
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
  mysql:
    image: mysql:latest
    ports:
      - "${FORWARD_HOST:-}:${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - ".docker/mysql/conf.d:/etc/mysql/conf.d:ro"
      - ".docker/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
